apiVersion: v2
name: warehouse-management
description: A Helm chart for Warehouse Management System
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - warehouse
  - management
  - microservices
  - dotnet

home: https://github.com/your-org/warehouse-management
sources:
  - https://github.com/your-org/warehouse-management

maintainers:
  - name: Development Team
    email: dev@warehouse.com

dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: rabbitmq
    version: "11.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: rabbitmq.enabled
  - name: redis
    version: "17.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
