apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-service
  namespace: warehouse-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alert-service
  template:
    metadata:
      labels:
        app: alert-service
    spec:
      containers:
      - name: alert-service
        image: warehouse/alert-service:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: warehouse-config
              key: ASPNETCORE_ENVIRONMENT
        - name: ConnectionStrings__DefaultConnection
          value: "Host=postgres-service;Database=alert_db;Username=warehouse_user;Password=warehouse_pass"
        - name: Redis__ConnectionString
          value: "redis-service:6379"
        - name: RabbitMQ__Host
          value: "rabbitmq-service"
        - name: RabbitMQ__Username
          value: "warehouse_user"
        - name: RabbitMQ__Password
          valueFrom:
            secretKeyRef:
              name: warehouse-secrets
              key: RABBITMQ_PASSWORD
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: alert-service-service
  namespace: warehouse-system
spec:
  selector:
    app: alert-service
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30006
  type: NodePort
