apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: warehouse-staging
  labels:
    app: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: ghcr.io/your-org/warehouse-management/api-gateway-dotnet:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: warehouse-config
              key: ASPNETCORE_ENVIRONMENT
        - name: ASPNETCORE_URLS
          valueFrom:
            configMapKeyRef:
              name: warehouse-config
              key: ASPNETCORE_URLS
        - name: JWT__Key
          valueFrom:
            secretKeyRef:
              name: warehouse-secrets
              key: JWT__Key
        - name: JWT__Issuer
          valueFrom:
            configMapKeyRef:
              name: warehouse-config
              key: JWT__Issuer
        - name: JWT__Audience
          valueFrom:
            configMapKeyRef:
              name: warehouse-config
              key: JWT__Audience
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: warehouse-staging
spec:
  selector:
    app: api-gateway
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
