apiVersion: v1
kind: Secret
metadata:
  name: warehouse-secrets
  namespace: warehouse-staging
type: Opaque
data:
  # JWT Secret Key (base64 encoded)
  JWT__Key: dGVzdC1zdXBlci1zZWNyZXQta2V5LXRoYXQtaXMtYXQtbGVhc3QtMzItY2hhcmFjdGVycy1sb25n
  
  # Database passwords (base64 encoded)
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  
  # RabbitMQ password (base64 encoded)
  RabbitMQ__Password: cGFzc3dvcmQ=
  
  # Email credentials (base64 encoded)
  Email__Username: eW91ci1lbWFpbEBnbWFpbC5jb20=
  Email__Password: eW91ci1hcHAtcGFzc3dvcmQ=
  
  # Twilio credentials (base64 encoded)
  Twilio__AccountSid: eW91ci10d2lsaW8tYWNjb3VudC1zaWQ=
  Twilio__AuthToken: eW91ci10d2lsaW8tYXV0aC10b2tlbg==
  Twilio__FromNumber: KzEyMzQ1Njc4OTA=
