apiVersion: v1
kind: ConfigMap
metadata:
  name: warehouse-config
  namespace: warehouse-management
data:
  NODE_ENV: "production"
  JWT_SECRET: "your-production-secret-key"
  RABBITMQ_URL: "amqp://admin:password@rabbitmq:5672"
  REDIS_URL: "redis://redis:6379"
  
  # Service URLs
  PRODUCT_SERVICE_URL: "http://product-service:3001"
  INVENTORY_SERVICE_URL: "http://inventory-service:3002"
  ORDER_SERVICE_URL: "http://order-service:3003"
  CUSTOMER_SERVICE_URL: "http://customer-service:3004"
  REPORTING_SERVICE_URL: "http://reporting-service:3005"
  ALERT_SERVICE_URL: "http://alert-service:3006"
  
  # Database configurations
  DB_USERNAME: "postgres"
  DB_PORT: "5432"
  
  # SMTP configuration
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"

---
apiVersion: v1
kind: Secret
metadata:
  name: warehouse-secrets
  namespace: warehouse-management
type: Opaque
data:
  # Base64 encoded values
  DB_PASSWORD: cGFzc3dvcmQ=  # password
  RABBITMQ_PASSWORD: cGFzc3dvcmQ=  # password
  SMTP_USER: eW91ci1lbWFpbEBnbWFpbC5jb20=  # your-email@gmail.com
  SMTP_PASS: eW91ci1hcHAtcGFzc3dvcmQ=  # your-app-password
